### ISSUE TITLE
Error in executing power.service

### ISSUE THREAD

**Issue by raoulrana** [iAbhinav/umun-os#1]
After copying and enabling power.service. I started the power service using

`sudo systemctl start power`

but the power did not come to the desired level 

`journalctl -u shiva -f`

I got this error when 

`journalctl -u power -f`

> pr 07 15:32:47 tulsaG003 systemd[1472]: power.service: Failed to execute command: No such file or directory
Apr 07 15:32:47 tulsaG003 systemd[1472]: power.service: Failed at step EXEC spawning /home/tulsa/d_server/power/power.sh: No such file or directory
Apr 07 15:32:47 tulsaG003 systemd[1]: power.service: Main process exited, code=exited, status=203/EXEC
Apr 07 15:32:47 tulsaG003 systemd[1]: power.service: Failed with result 'exit-code'.
Apr 07 15:33:08 tulsaG003 systemd[1]: power.service: Service hold-off time over, scheduling restart.
Apr 07 15:33:08 tulsaG003 systemd[1]: power.service: Scheduled restart job, restart counter is at 5.
Apr 07 15:33:08 tulsaG003 systemd[1]: Stopped power service.
Apr 07 15:33:08 tulsaG003 systemd[1]: power.service: Start request repeated too quickly.
Apr 07 15:33:08 tulsaG003 systemd[1]: power.service: Failed with result 'exit-code'.
Apr 07 15:33:08 tulsaG003 systemd[1]: Failed to start power service.

**Comment by iAbhinav** [comment]
The error is here

> Apr 07 15:32:47 tulsaG003 systemd[1472]: power.service: Failed at step EXEC spawning /home/tulsa/d_server/power/power.sh: No such file or directory

You need to replace

`/home/tulsa/d_server/power/power.sh:`

with 

`/home/tulsa/umun-os/power/power.sh:`

I will fix this asap.

**Comment by iAbhinav** [comment]
I have fixed this issue in the latest commit.

Kindly go to 

> cd /home/tulsa/umun-os

then

> sudo git pull
